### ISSUE TITLE
Support customized vault template creation

### ISSUE THREAD

**Issue by BraxWong** [BraxWong/Obsedian-Template-Generator#1]
### Subject of the issue
Currently, the generator can only generate one template with hardcoded settings. It would be nice to customize the template so everyone can create a vault that caters to their needs.

#### Tasks
- [x] New page to allow people to select the files they need and the quantity
- [x] Implement back-end functions to allow this to happen
- [x] Creating a JSON class to deserialize and serialize objects
