### ISSUE TITLE
Create Unit Tests 

### ISSUE THREAD

**Issue by BraxWong** [BraxWong/Obsedian-Template-Generator#14]
### Subject of the issue
Currently, the program is tested manually. To ensure the app is running as it is intended to, unit tests will be needed
#### Tasks
- [ ] Research Python test framework I can use
- [ ] Plan out test cases
- [ ] Implement test cases
- [ ] Ensure they all pass
- [ ] Perhaps integrate the testing phase using GitHub action?
