### ISSUE TITLE
Adding support for addition functionalities regarding Canva file type

### ISSUE THREAD

**Issue by BraxWong** [BraxWong/Obsedian-Template-Generator#3]
### Subject of the issue
Currently, the user of the app can only create a Canva-type file. However, in Obsidian MD, users can link different components using the Canva file as a JSON file type. Adding support for this will be necessary.

#### Tasks
- [ ] Expanding the visualization class
- [ ] Creating functions to take in files of different types to be linked together
- [ ] Creating a JSON class to deserialize and serialize objects
