### ISSUE TITLE
Adding support for importing different media into vault

### ISSUE THREAD

**Issue by BraxWong** [BraxWong/Obsedian-Template-Generator#4]
### Subject of the issue
Currently, the user of the app can only import things like markdown and canvas-type files.  It would be great if they were able to add things like a website, pictures, or even videos afterward.

#### Tasks
- [ ] Find out how this works in ObsidianMD
- [ ] Create separate classes for each media
- [ ] Try to integrate into Canvas files.
